coverage:
  #branch: main
  #bot: "codecov-io"
  #require_ci_to_pass: no

  status:
    project:
      default:
        # Whole-project must always have at least this coverage:
        target: 0
        # Whole-project test coverage is allowed to drop this much:
        threshold: 100
        # Notify only on pull requests
        only_pulls: true
    patch:
      default:
        # Changes must have at least this test coverage
        target: 0
        only_pulls: true

#ignore:
#  - "**/tests/*"

comment: false
